version: "3.9"

services:
  consul:
    image: hashicorp/consul:1.10.0
    container_name: consul
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      - scribd
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

networks:
  scribd:
    driver: bridge